name: E2E Tests

on:
  pull_request:
    branches: [main, staging]
  push:
    branches: [main, staging]
  schedule:
    # Run E2E tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        
      - name: Build application
        working-directory: ./frontend
        run: npm run build
        
      - name: Run essential E2E tests
        run: npm run test:e2e:essential
        env:
          # Use staging environment for E2E tests
          FRONTEND_URL: https://staging.adhub.tech
          BACKEND_URL: https://api-staging.adhub.tech
          NODE_ENV: staging
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
          
      - name: Upload test videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-videos
          path: test-results/
          retention-days: 7

  e2e-tests-local:
    name: E2E Tests (Local Server)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        
      - name: Run E2E tests with local server
        working-directory: ./frontend
        run: npm run test:e2e:essential
        env:
          # Use local development server
          FRONTEND_URL: http://localhost:3000
          NODE_ENV: development
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-local
          path: playwright-report/
          retention-days: 7 