name: Staging Quick Check

on:
  push:
    branches: [ staging ]

env:
  NODE_VERSION: '18'

jobs:
  quick-check:
    name: Quick TypeScript & Lint Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run TypeScript checks
        run: npm run type-check
        
      - name: Run ESLint
        run: npm run lint || echo "⚠️ Linting completed with warnings"
        
      - name: Build check
        run: npm run build
        
      - name: ✅ Quick check completed
        run: echo "✅ Staging quick check passed - ready for manual deployment if needed" 